<a href="https://colab.research.google.com/github/ninjaa1234/Learning_New/blob/main/Machine_Learning/02_Exrecise_Linear_reg_MV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Find out the salary of a guy with 2yr exp, 9 test scores, 6 interview score
#Find out the salary of a guy with 12yr exp, 10 test scores, 10 interview score

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [26]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [40]:
#filling the NaN on experience
df.experience=df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

In [47]:
!pip install word2number


  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5582 sha256=962d63368db0b91eb410e0c463efd82db5d69582e9944d326034f5b4c2ab0002
  Stored in directory: /root/.cache/pip/wheels/4b/c3/77/a5f48aeb0d3efb7cd5ad61cbd3da30bbf9ffc9662b07c9f879
Successfully built word2number


'from  word2number import w2n\ndf.experience=df.experience.apply(w2n.word_to_num)\ndf'

In [48]:
from  word2number import w2n
df.experience=df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [49]:
#filling the NaN on test_score
import math
median_test_score=math.floor(df["test_score(out of 10)"].median())
median_test_score

8

In [50]:
df["test_score(out of 10)"]=df["test_score(out of 10)"].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [51]:
reg=linear_model.LinearRegression()
reg.fit(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],df["salary($)"])

LinearRegression()

In [52]:
reg.predict([[2,9,6]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([53205.96797671])

In [53]:
x=np.array([2,9,6])
x

array([2, 9, 6])

In [55]:
m=reg.coef_
m

array([2812.95487627, 1845.70596798, 2205.24017467])

In [57]:
b=reg.intercept_
b

17737.263464337695

In [59]:
y=m.dot(x)+b
y

53205.96797671033