<a href="https://colab.research.google.com/github/ninjaa1234/Learning_New/blob/main/Machine_Learning/Hyper_parameter_Tuning_(GridSearchCV).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#The process of choosing the optimal parameter is called Hyperparameter Tuning

![picture](https://drive.google.com/uc?export=view&id=1KcvvzVjuSwVGlNi6cDDVFeAK80kq8FOg)

In [1]:
from sklearn.datasets import load_iris
iris=load_iris()

In [5]:
import pandas as pd
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower']=iris.target
df['flower']=df.flower.apply(lambda x : iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [6]:
X=iris.data
Y=iris.target

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=100)

#SVC


In [11]:
from sklearn.svm import SVC
svm=SVC(kernel="linear",C=30,gamma='auto')
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9777777777777777

This method is very manual and repetitive

In [12]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel="linear",C=30,gamma='auto'),X,Y,cv=5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [13]:
cross_val_score(SVC(kernel="rbf",C=30,gamma='auto'),X,Y,cv=5)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [14]:
cross_val_score(SVC(kernel="rbf",C=20,gamma='auto'),X,Y,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

for  looping the process

In [23]:
import numpy as np
kernels=['rbf','linear']
C=[1,10,20]
#avg_scores={}
for kval in kernels:
    for cval in C:
        cv_score=cross_val_score(SVC(kernel=kval,C=cval,gamma="auto"),X,Y,cv=5)
        #avg_scores[kval + "_" + str(cval)]=np.average(cv_scores)
        avg=np.average(cv_score)
        print("the average score of ",kval,"_",str(cval),"is: ",avg)
#avg_scores

the average score of  rbf _ 1 is:  0.9800000000000001
the average score of  rbf _ 10 is:  0.9800000000000001
the average score of  rbf _ 20 is:  0.9666666666666668
the average score of  linear _ 1 is:  0.9800000000000001
the average score of  linear _ 10 is:  0.9733333333333334
the average score of  linear _ 20 is:  0.9666666666666666


#GridSearch CV

For small class problems

In [25]:
from sklearn.model_selection import GridSearchCV

clf=GridSearchCV(SVC(gamma='auto'),{
    "C":[1,10,20],
    "kernel": ['rbf','linear']
},cv=5)
clf.fit(X,Y)
clf.cv_results_

{'mean_fit_time': array([0.00243573, 0.00123501, 0.00138092, 0.00111375, 0.00136733,
        0.00119677]),
 'mean_score_time': array([0.00091953, 0.00074449, 0.00071263, 0.00062089, 0.00071282,
        0.00066681]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'rank_test_score': array([1, 1, 1, 4, 5, 6], dtype=int32),
 'split0_test_score': array([0.96666667, 0.96

In [28]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.002436      0.001608         0.000920        0.000149       1   
1       0.001235      0.000095         0.000744        0.000220       1   
2       0.001381      0.000116         0.000713        0.000016      10   
3       0.001114      0.000080         0.000621        0.000021      10   
4       0.001367      0.000025         0.000713        0.000023      20   
5       0.001197      0.000059         0.000667        0.000054      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [30]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [33]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_

In [34]:
clf.best_score_

0.9800000000000001

In [35]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

For large class problems

In [39]:
from sklearn.model_selection import RandomizedSearchCV

rs=RandomizedSearchCV(SVC(gamma='auto'),{
    "C":[1,10,20],
    "kernel": ['rbf','linear']
},cv=5,
n_iter=2
)
rs.fit(X,Y)
rs.cv_results_

{'mean_fit_time': array([0.00163345, 0.00082402]),
 'mean_score_time': array([0.00061417, 0.00049548]),
 'mean_test_score': array([0.97333333, 0.98      ]),
 'param_C': masked_array(data=[10, 10],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'linear'}, {'C': 10, 'kernel': 'rbf'}],
 'rank_test_score': array([2, 1], dtype=int32),
 'split0_test_score': array([1.        , 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'std_fit_time': array([1.04323789e-03, 4.23681018e-05]),
 'std_score_time': array([0.00021373, 0.00018524]),
 'std_test_score': array([0.03887301, 0.01632993])}

In [40]:
dp=pd.DataFrame(rs.cv_results_)
dp[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.973333
1      10          rbf         0.980000

#Best Model

In [41]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [42]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 1}
2  logistic_regression    0.966667                   {'C': 5}