<a href="https://colab.research.google.com/github/ninjaa1234/Learning_New/blob/main/Machine_Learning/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Cross Validation helps us to find which machine learning method to choose
ie for example we can do the iris program in logistic regression or Random forest or Decision Tree 

![picture](https://drive.google.com/uc?export=view&id=1-0JoWcZ-b_wIbktALTmocfTUY36rvv9e)

![picture](https://drive.google.com/uc?export=view&id=1en3-1AFkeZV6SdJgxqSnZ6yu60Mk9bHL)

![picture](https://drive.google.com/uc?export=view&id=1F3WBHUKWDe9m3nanXZu9q2H92EG2Unvp)

![picture](https://drive.google.com/uc?export=view&id=1AWb7Tbj6ugNnuUXulZmYVvoEdYC-csAa)

![picture](https://drive.google.com/uc?export=view&id=1poNLfBBi9eDiXANz__TEtz_-LoTSgVTy)

![picture](https://drive.google.com/uc?export=view&id=1i2Ki2nNKYTdoapWp9-wMftZ-yQU6SOM9)

![picture](https://drive.google.com/uc?export=view&id=1Iu-i3ZjkVPulqItefXFnUGmSnaEya6sK)

But the problen with this is that assume the 70cent qns are from algebra and the rest 30cent are from calculus

#Therefore we use K Fold Cross Validation

![picture](https://drive.google.com/uc?export=view&id=1RAvxWPNohBM5WMnIE5DcakDHMzuvI2_O)

![picture](https://drive.google.com/uc?export=view&id=1V-F0yICvJt3cwHCfIwCcqLrRI7VRWeJY)

In [3]:
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

#Split it into train and test

In [32]:
from sklearn.model_selection import train_test_split
X=digits.data       #independent variables
Y=digits.target     #dependnent variables
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.3)

In [34]:
X_train

array([[ 0.,  4., 14., ..., 11.,  0.,  0.],
       [ 0.,  0.,  6., ...,  3.,  0.,  0.],
       [ 0.,  0.,  3., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  2., ...,  9.,  1.,  0.],
       [ 0.,  2., 15., ...,  2.,  0.,  0.]])

#Option 1 Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.958664546899841

#Option 2 SVM

In [36]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.985691573926868

#Option 3 Random Forest

In [37]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100)
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9610492845786963

#Each time you run the X_train,Y_train, its value keeps on changing.
ie the score of each machine learning model also keeps changing

#Option 4 K Fold Manually

In [38]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [39]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [40]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [41]:
get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.958664546899841

#StratifiedKFold Manually
uniform distribution happens in this KFold



In [42]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [43]:
scores_logistic = []
scores_svm = []
scores_rf = []

In [44]:
for train_index, test_index in folds.split(X,Y):
    X_train, X_test, Y_train, Y_test = X[train_index], X[test_index],Y[train_index], Y[test_index]
    scores_logistic.append(get_score(LogisticRegression(),X_train, X_test, Y_train, Y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, Y_train, Y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, Y_train, Y_test))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


#Find the average of the following scores

In [45]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [46]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [47]:
scores_rf

[0.9332220367278798, 0.9549248747913188, 0.9165275459098498]

In [48]:
X_train

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  1., 13., ..., 11.,  4.,  0.],
       [ 0.,  0.,  0., ..., 14.,  2.,  0.],
       [ 0.,  0.,  0., ...,  2.,  0.,  0.]])

#Cross_val_score
#KFold inbuild library

In [51]:
from sklearn.model_selection import cross_val_score

In [52]:
cross_val_score(LogisticRegression(),X,Y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [55]:
cross_val_score(SVC(),X,Y)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=40),X,Y)

array([0.91944444, 0.89444444, 0.95821727, 0.9637883 , 0.91922006])

#Parameter Tuning
Comparing the multiple n_estimators

In [57]:
cross_val_score(RandomForestClassifier(n_estimators=40),X,Y)

array([0.91944444, 0.90833333, 0.94428969, 0.96657382, 0.9275766 ])

In [58]:
cross_val_score(RandomForestClassifier(n_estimators=30),X,Y)

array([0.92777778, 0.91388889, 0.96100279, 0.96657382, 0.9275766 ])

In [59]:
cross_val_score(RandomForestClassifier(n_estimators=10),X,Y)

array([0.90277778, 0.84444444, 0.90807799, 0.94150418, 0.89415042])