<a href="https://colab.research.google.com/github/ninjaa1234/Learning_New/blob/main/Machine_Learning/Linear_Regression_MV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![picture](https://drive.google.com/uc?export=view&id=1-Xcwr6VfeP-RuQZJ6t0CFGFV7RadDVde)

![picture](https://drive.google.com/uc?export=view&id=1vRqrDg0IlPWCpTiwSylRLZ2SyFlJFopC)

![picture](https://drive.google.com/uc?export=view&id=1Q8dWc1whCBY66JfXetEAYBuKSm8G7O1S)

#Handle that null value in data
#Linear Regression

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
#handling na values with mean of the data
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [6]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
reg=linear_model.LinearRegression()
#independent variables in df[[]], targert/dependent variables in df.
reg.fit(df[["area",'bedrooms','age']],df.price)

LinearRegression()

In [18]:
#x are the variables
x=np.array([3000,3,40])

In [10]:
#m means m1,m2,m3
m=reg.coef_
m

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
#b means y intercept
b=reg.intercept_
b

221323.00186540396

#Predicting the price when area is 3000, rooms is 3, and age is 40

In [17]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([498408.25158031])

#Mathematical Method

In [22]:
y=m.dot(x)+b
y

498408.2515803067

#Predicting the price when area is 2500, rooms is 4, and age is 5

In [23]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([578876.03748933])