<a href="https://colab.research.google.com/github/ninjaa1234/Learning_New/blob/main/Machine_Learning/Save_Model_using_Jobob_and_Pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

#Predict the price of 5000sq feet home udong LinearRegression

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/4_save_model/homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [15]:
reg=linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [4]:
reg.coef_

array([135.78767123])

In [5]:
reg.intercept_

180616.43835616432

In [8]:
reg.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

#pickle module()

In [11]:
import pickle

In [13]:
with open('reg_pickle','wb') as f:
    pickle.dump(reg,f)

In [16]:
with open('reg_pickle','rb') as f:
    mp=pickle.load(f)

In [17]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [23]:
!pip install joblib

In [ ]:
import sklearn.