<a href="https://colab.research.google.com/github/ninjaa1234/Learning_New/blob/main/Numpy/np_basic_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#1D-array

In [2]:
a=np.array([5,6,9])
a

array([5, 6, 9])

#2D-Array

In [5]:
a=np.array([[1,2],[3,4],[5,6]])

#prints the number of dimensions of array
a.ndim

2

In [6]:
a=np.array([[1,2],[3,4],[5,6]])

#prints the bit size of array
a.itemsize


8

In [9]:
a=np.array([[1,2],[3,4],[5,6]])

#change datatypeof elements in array
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
print(a.itemsize)
print(a)


8
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [15]:
a=np.array([[1,2],[3,4],[5,6]])

#change datatypeof elements in array
a=np.array([[1,2],[3,4],[5,6]], dtype=complex)
print(a.itemsize)
print(a)

16
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [10]:
a=np.array([[1,2],[3,4],[5,6]])

#size of array, ie no of induvitual elemets in array
a.size

6

In [11]:
a=np.array([[1,2],[3,4],[5,6]])

#shape of array
a.shape

(3, 2)

#zeros and one()

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#range()

In [18]:
np.arange(1,5)

array([1, 2, 3, 4])

#linspace()

In [20]:
#prints 10 linearly spaced numbers between 1 and 5
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#reshape()

In [24]:
a=np.array([[1,2],[3,4],[5,6]])
shape=a.shape
reshape=a.reshape(2,3)
print("the shape of starting array is:",shape)
print("The reshaped array of (2,3) is:",reshape)

the shape of starting array is: (3, 2)
The reshaped array of (2,3) is: [[1 2 3]
 [4 5 6]]


#raven()
makes the array 1D

In [26]:
a=np.array([[1,2],[3,4],[5,6]])
a.ravel()


array([1, 2, 3, 4, 5, 6])

#functions in array

In [28]:
a=np.array([[1,2],[3,4],[5,6]])
a.min()

1

In [29]:
a=np.array([[1,2],[3,4],[5,6]])
a.max()

6

In [30]:
a=np.array([[1,2],[3,4],[5,6]])
a.sum()

21

In [31]:
a=np.array([[1,2],[3,4],[5,6]])
#sums up all elements in y axis
a.sum(axis=0)


array([ 9, 12])

In [32]:
a=np.array([[1,2],[3,4],[5,6]])
#sums up all elemsnts in x axis
a.sum(axis=1)

array([ 3,  7, 11])

In [33]:
a=np.array([[1,2],[3,4],[5,6]])
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [34]:
a=np.array([[1,2],[3,4],[5,6]])
np.std(a)

1.707825127659933

#Operations in array

In [35]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a+b

array([[ 6,  8],
       [10, 12]])

In [36]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

#matrix product
a.dot(b)

array([[19, 22],
       [43, 50]])