<a href="https://colab.research.google.com/github/ninjaa1234/Learning_New/blob/main/Numpy/np_iterate_and_numpy_editor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#run for foor loop

In [4]:
#iterating over row

for row in a:
  print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [6]:
#iterating over each cell

for row in a:
  for cell in row:
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


#use flatten method() 

In [7]:
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


#numpy function nditer()

In [8]:
#prints cell row order

for x in np.nditer(a,order='C'):
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
#prints cell column order


for x in np.nditer(a,order='F'):
  print(x)

0
4
8
1
5
9
2
6
10
3
7
11


#supply flags in numpy function nditer()

In [13]:
#prints in column order
for x in np.nditer(a,order='F',flags=['external_loop']):
  print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [14]:
#prints in row order
for x in np.nditer(a,order='C',flags=['external_loop']):
  print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


#Modify array values while iterating

In [15]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

#Iterate two broadcastable arrays concurrently

In [16]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [17]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [19]:
#either both arrays should have same size
#or one of the arrays dimension should be 1

for x,y in np.nditer([a,b]):
  print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
