<a href="https://colab.research.google.com/github/ninjaa1234/Learning_New/blob/main/Numpy/np_slicing_stacking_arrays%2C_indexing_with_boolean_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
n=[6,7,8]
n[0:3]

[6, 7, 8]

In [4]:
a=np.array([6,7,8])
a[0:3]

array([6, 7, 8])

In [10]:
a=np.array([[6,7,8],[5,6,7],[7,8,9]])
a

array([[6, 7, 8],
       [5, 6, 7],
       [7, 8, 9]])

In [11]:
a=np.array([[6,7,8],[5,6,7],[7,8,9]])
a[1,2]

7

In [12]:
a=np.array([[6,7,8],[5,6,7],[7,8,9]])
a[0:2,2]

array([8, 7])

In [13]:
a=np.array([[6,7,8],[5,6,7],[7,8,9]])
a[-1]

array([7, 8, 9])

In [14]:
a=np.array([[6,7,8],[5,6,7],[7,8,9]])
a[-1,0:2]

array([7, 8])

In [19]:
a=np.array([[6,7,8],[5,6,7],[7,8,9]])
a[:,1:3]

array([[7, 8],
       [6, 7],
       [8, 9]])

#Iterate in array

In [20]:
a=np.array([[6,7,8],[5,6,7],[7,8,9]])
for row in a:
  print(row)

[6 7 8]
[5 6 7]
[7 8 9]


In [22]:
a=np.array([[6,7,8],[5,6,7],[7,8,9]])

#prints out every element in array
for cell in a.flat:
  print(cell)

6
7
8
5
6
7
7
8
9


#Stacking two arrays together

In [25]:
a=np.arange(6)


array([0, 1, 2, 3, 4, 5])

In [30]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [31]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
np.hstack((a,b))
#horizontal stacking

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [36]:
np.vstack((a,b))
#vertical stacking

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [38]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
#splitting array into 3 horizontally equal length array

np.hsplit(a,3)

In [46]:
result=np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [44]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [45]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [50]:
#splitting array into 2 vertically equal length array

np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [47]:
result=np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [49]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

#indexing with boolean

In [52]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
#extracting all elements greater than 4
b=a>4
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [57]:
#extracting all elements greater than 4 and replace them with -1
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])